export default {
    files: [
        {
            _id: 1,
            name: 'dsdas',
            surname: 'dsaddas',
            age: 1,
            color: 'red',
            dogName: 'rex',
            momName: 'natasha',
            dadName: 'sasha',
            group: 'queen',
            model: 't14s',
            timestamp: '06.10.2020'
        },
        {
            _id: 2,
            name: 'dsdas2',
            surname: 'dsaddas2',
            age: 2,
            color: 'red2',
            dogName: 'rex2',
            momName: 'natasha2',
            dadName: 'sasha2',
            group: 'queen2',
            model: 't14s2',
            timestamp: '06.10.2021'
        },
        {
            _id: 1,
            name: 'dsdas',
            surname: 'dsaddas',
            age: 1,
            color: 'red',
            dogName: 'rex',
            momName: 'natasha',
            dadName: 'sasha',
            group: 'queen',
            model: 't14s',
            timestamp: '06.10.2020'
        },
        {
            _id: 2,
            name: 'dsdas2',
            surname: 'dsaddas2',
            age: 2,
            color: 'red2',
            dogName: 'rex2',
            momName: 'natasha2',
            dadName: 'sasha2',
            group: 'queen2',
            model: 't14s2',
            timestamp: '06.10.2021'
        },
        {
            _id: 1,
            name: 'dsdas',
            surname: 'dsaddas',
            age: 1,
            color: 'red',
            dogName: 'rex',
            momName: 'natasha',
            dadName: 'sasha',
            group: 'queen',
            model: 't14s',
            timestamp: '06.10.2020'
        },
        {
            _id: 2,
            name: 'dsdas2',
            surname: 'dsaddas2',
            age: 2,
            color: 'red2',
            dogName: 'rex2',
            momName: 'natasha2',
            dadName: 'sasha2',
            group: 'queen2',
            model: 't14s2',
            timestamp: '06.10.2021'
        },
        {
            _id: 1,
            name: 'dsdas',
            surname: 'dsaddas',
            age: 1,
            color: 'red',
            dogName: 'rex',
            momName: 'natasha',
            dadName: 'sasha',
            group: 'queen',
            model: 't14s',
            timestamp: '06.10.2020'
        },
        {
            _id: 2,
            name: 'dsdas2',
            surname: 'dsaddas2',
            age: 2,
            color: 'red2',
            dogName: 'rex2',
            momName: 'natasha2',
            dadName: 'sasha2',
            group: 'queen2',
            model: 't14s2',
            timestamp: '06.10.2021'
        },
        {
            _id: 1,
            name: 'dsdas',
            surname: 'dsaddas',
            age: 1,
            color: 'red',
            dogName: 'rex',
            momName: 'natasha',
            dadName: 'sasha',
            group: 'queen',
            model: 't14s',
            timestamp: '06.10.2020'
        },
        {
            _id: 2,
            name: 'dsdas2',
            surname: 'dsaddas2',
            age: 2,
            color: 'red2',
            dogName: 'rex2',
            momName: 'natasha2',
            dadName: 'sasha2',
            group: 'queen2',
            model: 't14s2',
            timestamp: '06.10.2021'
        },
        {
            _id: 1,
            name: 'dsdas',
            surname: 'dsaddas',
            age: 1,
            color: 'red',
            dogName: 'rex',
            momName: 'natasha',
            dadName: 'sasha',
            group: 'queen',
            model: 't14s',
            timestamp: '06.10.2020'
        },
        {
            _id: 2,
            name: 'dsdas2',
            surname: 'dsaddas2',
            age: 2,
            color: 'red2',
            dogName: 'rex2',
            momName: 'natasha2',
            dadName: 'sasha2',
            group: 'queen2',
            model: 't14s2',
            timestamp: '06.10.2021'
        },
        {
            _id: 1,
            name: 'dsdas',
            surname: 'dsaddas',
            age: 1,
            color: 'red',
            dogName: 'rex',
            momName: 'natasha',
            dadName: 'sasha',
            group: 'queen',
            model: 't14s',
            timestamp: '06.10.2020'
        },
        {
            _id: 2,
            name: 'dsdas2',
            surname: 'dsaddas2',
            age: 2,
            color: 'red2',
            dogName: 'rex2',
            momName: 'natasha2',
            dadName: 'sasha2',
            group: 'queen2',
            model: 't14s2',
            timestamp: '06.10.2021'
        },
        {
            _id: 1,
            name: 'dsdas',
            surname: 'dsaddas',
            age: 1,
            color: 'red',
            dogName: 'rex',
            momName: 'natasha',
            dadName: 'sasha',
            group: 'queen',
            model: 't14s',
            timestamp: '06.10.2020'
        },
        {
            _id: 2,
            name: 'dsdas2',
            surname: 'dsaddas2',
            age: 2,
            color: 'red2',
            dogName: 'rex2',
            momName: 'natasha2',
            dadName: 'sasha2',
            group: 'queen2',
            model: 't14s2',
            timestamp: '06.10.2021'
        },
        {
            _id: 1,
            name: 'dsdas',
            surname: 'dsaddas',
            age: 1,
            color: 'red',
            dogName: 'rex',
            momName: 'natasha',
            dadName: 'sasha',
            group: 'queen',
            model: 't14s',
            timestamp: '06.10.2020'
        },
        {
            _id: 2,
            name: 'dsdas2',
            surname: 'dsaddas2',
            age: 2,
            color: 'red2',
            dogName: 'rex2',
            momName: 'natasha2',
            dadName: 'sasha2',
            group: 'queen2',
            model: 't14s2',
            timestamp: '06.10.2021'
        },
        {
            _id: 1,
            name: 'dsdas',
            surname: 'dsaddas',
            age: 1,
            color: 'red',
            dogName: 'rex',
            momName: 'natasha',
            dadName: 'sasha',
            group: 'queen',
            model: 't14s',
            timestamp: '06.10.2020'
        },
        {
            _id: 2,
            name: 'dsdas2',
            surname: 'dsaddas2',
            age: 2,
            color: 'red2',
            dogName: 'rex2',
            momName: 'natasha2',
            dadName: 'sasha2',
            group: 'queen2',
            model: 't14s2',
            timestamp: '06.10.2021'
        },
        {
            _id: 1,
            name: 'dsdas',
            surname: 'dsaddas',
            age: 1,
            color: 'red',
            dogName: 'rex',
            momName: 'natasha',
            dadName: 'sasha',
            group: 'queen',
            model: 't14s',
            timestamp: '06.10.2020'
        },
        {
            _id: 2,
            name: 'dsdas2',
            surname: 'dsaddas2',
            age: 2,
            color: 'red2',
            dogName: 'rex2',
            momName: 'natasha2',
            dadName: 'sasha2',
            group: 'queen2',
            model: 't14s2',
            timestamp: '06.10.2021'
        },
        {
            _id: 1,
            name: 'dsdas',
            surname: 'dsaddas',
            age: 1,
            color: 'red',
            dogName: 'rex',
            momName: 'natasha',
            dadName: 'sasha',
            group: 'queen',
            model: 't14s',
            timestamp: '06.10.2020'
        },
        {
            _id: 2,
            name: 'dsdas2',
            surname: 'dsaddas2',
            age: 2,
            color: 'red2',
            dogName: 'rex2',
            momName: 'natasha2',
            dadName: 'sasha2',
            group: 'queen2',
            model: 't14s2',
            timestamp: '06.10.2021'
        },
        
    ]
}